_production_templates:  # FIXME
  - &production_stuff
    - !Copy
      source: /work/config/production
      path: /config
    - !EnsureDir /local
    - !EnsureDir /log
    - !EnsureDir /lithos
    - !Copy
      source: /work/lithos/production
      path: /lithos
  - &production_host_resolution
    - !EnsureDir /state
    - !Sh |
        /bin/ln -sfn /state/hosts /etc/hosts
        /bin/ln -sfn /state/resolv.conf /etc/resolv.conf

containers:
  celery-production:
    setup:
      - !Container celery-dev
      - !*Unpack
        - *production_stuff
      - !Copy
        source: /work/celery_tasks
        path: /app
      - !Sh python3 -m compileall /app
      - !*Unpack
        - *production_host_resolution
    volumes:
      /state: !Tmpfs
    resolv-conf-path: /state/resolv.conf
    hosts-file-path: /state/hosts

  redis-production:
    setup:
      - !Container redis-dev
      - !*Unpack
        - *production_stuff
        - *production_host_resolution
    volumes:
      /state: !Tmpfs
    resolv-conf-path: /state/resolv.conf
    hosts-file-path: /state/hosts

  mysql-production:
    setup:
      - !Container mysql-dev
      - !*Unpack
        - *production_stuff
      - !Copy
        source: /config/mysql
        path: /etc/mysql
      - !*Unpack
        - *production_host_resolution
    volumes:
      /state: !Tmpfs
    resolv-conf-path: /state/resolv.conf
    hosts-file-path: /state/hosts

  php-production:
    setup:
      - !Container _php-base
      - !*Unpack
        - *production_stuff
      - !Copy
        source: /config/php
        path: /etc/php/7.2/fpm
      - !EnsureDir /app
      - !Copy
        source: /work
        path: /app
        include-regex: ^(classes|settings|engine|templates)/*
      - !Copy
        source: /work/index.php
        path: /app/index.php
      # FIXME: Implicit locale build
      - !BuildDeps [git]
      - !Sh git describe --always > /app/backend.version
      - !Build
        container: assets
        source: /static
        path: /static
      - !*Unpack
        - *production_host_resolution
    volumes:
      /state: !Tmpfs
    resolv-conf-path: /state/resolv.conf
    hosts-file-path: /state/hosts

  elastic-production:
    setup:
      - !Container elastic-dev
      - !*Unpack
        - *production_stuff
      - !Copy
        source: /config/elasticsearch
        path: /etc/elasticsearch
      - !*Unpack
        - *production_host_resolution
    volumes:
      /state: !Tmpfs
    resolv-conf-path: /state/resolv.conf
    hosts-file-path: /state/hosts
