version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: docker/tabun/Dockerfile
      target: backend
    volumes:
      - storage:/storage
      - ./index.php:/app/index.php
      - ./engine:/app/engine
      - ./classes:/app/classes
      - ./settings:/app/settings
      - ./templates:/app/templates
      - static:/app/static
      - ./docker/tabun/nginx.conf:/etc/nginx/sites-enabled/default
      - ./docker/tabun/tabun-dev.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - db
      - redis
      - tasks
    environment:
      MARIADB_USER: ${MARIADB_USER:-tabun}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-tabun}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-tabun}
    ports:
      - '8000:80'

  frontend:
    build:
      context: .
      dockerfile: docker/tabun/Dockerfile
      target: frontend-dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/templates/skin/synio/locale/ru_RU/LC_MESSAGES
      - static:/app/static
  db:
    build:
      context: .
      dockerfile: docker/mariadb/Dockerfile
    environment:
      MARIADB_USER: ${MARIADB_USER:-tabun}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-tabun}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-tabun}
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: ${MARIADB_ALLOW_EMPTY_ROOT_PASSWORD:-true}
    volumes:
      - ./docker/mariadb/conf.d:/etc/mysql/conf.d/conf.d
      - db:/var/lib/mysql

  tasks:
    build:
      context: .
      dockerfile: docker/celery/Dockerfile
    depends_on:
      - redis
    environment:
      - CELERY_MAILER_HOST=mailcatcher
      - CELERY_MAILER_PORT=1025
    volumes:
      - ./docker/celery/tasks.py:/app/tasks.py

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis:/data

  elastic:
    image: elasticsearch:8.2.0
    volumes:
      - elastic:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

  kibana:
    image: kibana:8.2.0
    ports:
      - '5601:5601'

  mailcatcher:
    image: schickling/mailcatcher:latest
    ports:
      - '1080:1080'

volumes:
  db: { }
  redis: { }
  storage: { }
  elastic: { }
  static: {}
