version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: docker/tabun/Dockerfile
      target: application
    volumes:
      - storage:/storage
    depends_on:
      - db
      - redis
      - tasks
    environment:
      MARIADB_USER: ${MARIADB_USER:-tabun}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-tabun}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-tabun}
    ports:
      - '8000:80'

  db:
    build:
      context: .
      dockerfile: docker/mariadb/Dockerfile
    environment:
      MARIADB_USER: ${MARIADB_USER:-tabun}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-tabun}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-tabun}
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: ${MARIADB_ALLOW_EMPTY_ROOT_PASSWORD:-true}
    volumes:
      - db:/var/lib/mysql

  tasks:
    build:
      context: .
      dockerfile: docker/celery/Dockerfile
    depends_on:
      - redis
    environment:
      - CELERY_MAILER_HOST=mailcatcher
      - CELERY_MAILER_PORT=1025

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis:/data

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
    volumes:
      - elastic:/usr/share/elasticsearch/data
    environment:
      - cluster.name=tabun
      - discovery.type=single-node
      - path.repo=/usr/share/elasticsearch
      - "ES_JAVA_OPTS=-Xms512m -Xmx2048m"
      - xpack.security.enabled=false

  mailcatcher:
    image: schickling/mailcatcher:latest
    ports:
      - '1080:1080'

volumes:
  db: { }
  redis: { }
  storage: { }
  elastic: { }
