version: '3.7'

services: 
  php-fpm:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: dev
    volumes:
      - .:/app

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - '8000:80'
    volumes:
      - .:/app
    depends_on: 
      - php-fpm

  frontend:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: frontend
    volumes:
      - .:/app
    command: npx webpack watch -p --color
